[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
podman-api = "0.10"
futures-util = "0.3"
dotenvy = "0.15"
uuid = { version = "1", features = ["v4"] }
